### ISSUE TITLE
Uncaught TypeError: Cannot read property 'load' of undefined

### ISSUE THREAD

**Issue by Nfinished** [anthonyjgrove/react-google-login#318]
Experienced when using the hook like so:

```js
import { useGoogleLogin } from 'react-google-login'

import config from 'config'

import { useActions, GoogleActions } from 'modules'

const SCOPES = [
  'email',
  'profile',
  'openid',
  //... a few more scopes
]

export default () => {
  const actions = useActions({
    googleLoginSuccess: GoogleActions.googleLoginSuccess,
    googleLoginPending: GoogleActions.googleLoginPending,
    googleLoginFailed: GoogleActions.googleLoginFailed,
  })

  return useGoogleLogin({
    clientId: config.GOOGLE_CLIENTID,
    cookiePolicy: 'single_host_origin',
    scope: SCOPES.join(' '),
    onSuccess: actions.googleLoginSuccess,
    onFailure: actions.googleLoginFailed,
    onRequest: actions.googleLoginPending,
  })
}
```

The component version is being used elsewhere in the application without issue. Let me know what other information you need to debug.

**Comment by Nfinished** [comment]
Looks like `gapi` isn't defined when this line is hit.
https://github.com/anthonyjgrove/react-google-login/blob/master/src/use-google-login.js#L85

**Comment by sp-daniel-sanchez** [comment]
You've been able to solve the issue, @Nfinished ?

**Comment by Nfinished** [comment]
I have not.

**Comment by sp-daniel-sanchez** [comment]
I'll go with the GoogleLogin component and wait for the fix then, ty!

**Comment by zelardiel** [comment]
I had the same problem, and i have found the reason why this happens.

The hook does not by default set the jsSrc.
If you do the following it should work:

`return useGoogleLogin({
    clientId: config.GOOGLE_CLIENTID,
    cookiePolicy: 'single_host_origin',
    scope: SCOPES.join(' '),
    onSuccess: actions.googleLoginSuccess,
    onFailure: actions.googleLoginFailed,
    onRequest: actions.googleLoginPending,
    jsSrc: 'https://apis.google.com/js/api.js'
  })`

**Comment by Nfinished** [comment]
> I had the same problem, and i have found the reason why this happens.
> 
> The hook does not by default set the jsSrc.
> If you do the following it should work:
> 
> ```
> return useGoogleLogin({
>     clientId: config.GOOGLE_CLIENTID,
>     cookiePolicy: 'single_host_origin',
>     scope: SCOPES.join(' '),
>     onSuccess: actions.googleLoginSuccess,
>     onFailure: actions.googleLoginFailed,
>     onRequest: actions.googleLoginPending,
>     jsSrc: 'https://apis.google.com/js/api.js'
>   })
> ```

Thank you! This was the solution, I'll throw up a pr

**Comment by achtan** [comment]
pls push new version to npm

**Comment by anthonyjgrove** [comment]
done, v5.1.10

**Comment by BjoernRave** [comment]
I still have this problem. Do you think running this inside a chrome extension/iframe could be the reason?

**Comment by vaibhav1805** [comment]
@BjoernRave did you make it work inside the chrome extension? Even i'm struggling with the same.

**Comment by sabinbogati1** [comment]
@BjoernRave  @vaibhav1805  have you guys find solution for this problem? I am also struggling with the same issue

**Comment by BjoernRave** [comment]
nope, was not able to make it work...

**Comment by sabinbogati1** [comment]
@BjoernRave  any other solution you tried for google login in chrome extension which has iframe?

**Comment by mhatvan** [comment]
Did anyone figure out how to make Google auth work inside a Chrome extension with manifest v3?

**Comment by davinun99** [comment]
Also having problems with the button and chrome extensions here
